name: Release

on: push

jobs:
  # build-linux:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1

  #     - name: Install latest rust toolchain
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         target: x86_64-unknown-linux-musl
  #         default: true
  #         override: true

  #     - name: Build
  #       run: |
  #         cargo build --all --release --target x86_64-unknown-linux-musl
  #         cd target/x86_64-unknown-linux-musl/release
  #         strip replibyte
  #         EVENT_DATA=$(cat "$GITHUB_EVENT_PATH")
  #         RELEASE_NAME=$(echo "$EVENT_DATA" | jq -r .release.tag_name)
  #         FILE=replibyte_${RELEASE_NAME}_x86_64-unknown-linux-musl
  #         mv replibyte $FILE
  #         tar -czvf ${FILE}.tar.gz $FILE && rm $FILE
  #         sha256sum "${FILE}.tar.gz" | cut -d ' ' -f 1 > ${FILE}.sha256sum

  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         files: |
  #           target/release/replibyte_*
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          target: x86_64-pc-windows-gnu
          override: true

      - name: Build for windows
        run: cargo build --all --release --target x86_64-pc-windows-gnu

      - name: Prepare release
        run: |
          cd target/x86_64-pc-windows-gnu/release
          strip replibyte
          EVENT_DATA=$(cat "$GITHUB_EVENT_PATH")
          RELEASE_NAME=$(echo "$EVENT_DATA" | jq -r .release.tag_name)
          FILE=replibyte_${RELEASE_NAME}_x86_64-pc-windows-gnu
          mv replibyte $FILE
          tar -czvf ${FILE}.tar.gz $FILE && rm $FILE
          sha256sum "${FILE}.tar.gz" | cut -d ' ' -f 1 > ${FILE}.sha256sum

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/replibyte.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: |
          docker run --rm \
            --volume "${PWD}":/root/src \
            --workdir /root/src \
            joseluisq/rust-linux-darwin-builder:1.60.0 \
            sh -c "CC=o64-clang CXX=o64-clang++ cargo build --target x86_64-apple-darwin"

      - name: Prepare release
        run: |
          cd target/x86_64-apple-darwin/release
          strip replibyte
          EVENT_DATA=$(cat "$GITHUB_EVENT_PATH")
          RELEASE_NAME=$(echo "$EVENT_DATA" | jq -r .release.tag_name)
          FILE=replibyte_${RELEASE_NAME}_x86_64-apple-darwin
          mv replibyte $FILE
          tar -czvf ${FILE}.tar.gz $FILE && rm $FILE
          sha256sum "${FILE}.tar.gz" | cut -d ' ' -f 1 > ${FILE}.sha256sum

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/replibyte_darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
