name: Release

on:
  release:
    types:
      - published
      - created

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          default: true
          override: true

      - name: Build
        run: |
          cargo build --all --release
          strip target/release/replibyte
          RELEASE_NAME=$(echo "$GITHUB_EVENT_PATH" | jq -r .release.tag_name)
          NAME=replibyte_${RELEASE_NAME}_x86_64-unknown-linux-musl
          mv target/release/replibyte /target/release/$NAME
          tar -czvf ${NAME}.tar.gz $NAME
          sha256sum "${target/release/NAME}" | cut -d ' ' -f 1 > target/release/{$NAME}.sha256sum

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/replibyte_${$(echo "$GITHUB_EVENT_PATH" | jq -r .release.tag_name)}_x86_64-unknown-linux-musl
            target/release/replibyte_${$(echo "$GITHUB_EVENT_PATH" | jq -r .release.tag_name)}_x86_64-unknown-linux-musl.sha256sum
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # build-win:
  #   runs-on: windows-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1

  #     - name: Install latest rust toolchain
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         default: true
  #         override: true

  #     - name: Build
  #       run: cargo build --all --release

  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         files: target/release/replibyte.exe
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # build-mac:
  #   runs-on: macos-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1

  #     - name: Install latest rust toolchain
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         target: x86_64-apple-darwin
  #         default: true
  #         override: true

  #     - name: Build for mac
  #       run: cargo build --all --release && strip target/release/replibyte && mv target/release/replibyte target/release/replibyte_darwin

  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         files: |
  #           target/release/replibyte_darwin
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
