on:
  release:
    types:
      - published
      - created

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          EXTRA_FILES: "README.md"
          SRC_DIR: "replibyte"
          MINIFY: "yes"
  publish-on-homebrew:
    runs-on: ubuntu-latest
    needs: [ release ]
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          # Required, custom GitHub access token with the 'public_repo' and 'workflow' scopes
          token: ${{ secrets.PERSONAL_TOKEN }}
          # Optional, defaults to homebrew/core
          tap: Qovery/homebrew-replibyte
          # Formula name, required
          formula: replibyte
          # Optional, will be determined automatically
          tag: ${{ github.ref }}
          # Optional, will be determined automatically
          revision: ${{ github.sha }}
          # Optional, if don't want to check for already open PRs
          force: false # true
